### ISSUE TITLE
同一行表单项，左侧拖拽到右侧有问题

### ISSUE THREAD

**Issue by dingxyang** [mingdaocom/pd-openweb#5]
![chrome-capture](https://user-images.githubusercontent.com/26344414/164158710-18c8dfd3-751e-43fe-9a2e-c025040778b2.gif)

insertControlInSameLine 要处理同一行，左到右的问题

**Comment by qiujunbiao** [comment]
我们这边测试是没有问题的，请详细描述一下问题

**Comment by xyding1993** [comment]
比如上图 A B C
拖拽A组件到C组件的左侧，期望自动布局调整为B A C
但是实际为B C A

**Comment by xyding1993** [comment]
> 比如上图 A B C
> 拖拽A组件到C组件的左侧，期望自动布局调整为B A C
> 但是实际为B C A

**Comment by qiujunbiao** [comment]
ok  已经复现  后续版本会进行修复
