### ISSUE TITLE
安装开发环境出错

### ISSUE THREAD

**Issue by Chen-Zhihui** [mingdaocom/pd-openweb#7]
version 5.4.2

npm install 报错

'Log files:
/home/d/.npm/_logs/2024-06-03T22_35_09_885Z-debug-0.log

# npm resolution error report

While resolving: mingdao-web@10.1.0
Found: react@16.14.0
node_modules/react
  react@"16" from the root project

Could not resolve dependency:
peer react@"^15.4.2" from react-addons-css-transition-group@15.6.2
node_modules/react-addons-css-transition-group
  react-addons-css-transition-group@"^15.6.2" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

**Comment by peidayu** [comment]
加上 npm i 加上 --force 就可以了
